export PS1="[\u@\[\033[1;34m\]\h:\[\033[0;37m\]\w]\[\033[0m\]$ "

alias ls='ls -G'
alias la='ls -Ga'
alias ll='ls -lGa'
alias rm='rm -i'
alias mv='mv -i'
alias psql='/usr/local/bin/psql'
alias createdb='/usr/local/bin/createdb'
alias git-show-files='git diff-tree --no-commit-id --name-only -r'
alias git-repo-contents='git ls-tree --full-tree -r HEAD'
alias workladder='. /opt/ladder/venv/bin/activate'
set -o noclobber
shopt -s extglob
